CREATE TABLE SERVERSTORE (INFRAID INT AUTO_INCREMENT PRIMARY KEY,SERVER_NAME VARCHAR(250) , SERVER_TYPE VARCHAR(250));

INSERT INTO SERVERSTORE (FIRST_NAME,LAST_NAME) VALUES ("GBLT401876","CLOUDSERVE");